databases:
  - name: db
    plan: free
    databaseName: school_tracker_db
    user: admin

services:
  - type: web
    plan: free
    name: school-incident-tracker
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd app && python -m gunicorn school_incident_tracker.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
